language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade setuptools coverage
  - pip install --editable .[dev]
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest -s -vv --cov=./wampy

env:
  - WAMPY_ASYNC_NAME=eventlet
  - WAMPY_ASYNC_NAME=gevent

after_success:
  - coveralls
