language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - pip install --upgrade setuptools
  - pip install .
  - pip install --editable .[dev]
  - py.test ./test -s -vv

env:
  - WAMPY_ASYNC_NAME=eventlet
  - WAMPY_ASYNC_NAME=gevent
